### ISSUE TITLE
Source for DLL?

### ISSUE THREAD

**Issue by zepalmer** [Gedemon/Civ5-MultiPlayer-ModsPack-Maker#2]
Would it be possible for the repository to contain the source for `CvGameCore_MPMPMaker.dll`, or is that a presumptuous request?  I'm thinking about building a Linux CLI tool based on this delightful code, but I'm not entirely sure what happens behind the magic routines like `Game.CopyDataToMPMP`.

Thanks for this mod!  My wife and I stress the game with gigabytes of mods at a time; this makes Civ V a much better experience for us.

**Comment by Gedemon** [comment]
Hi  !

The source is also on github, with all my others DLL

**Comment by zepalmer** [comment]
Oh, I'm sorry; I didn't realize that.

I also notice that the utilities in that DLL pretty much seem to be file operations that the Civ 5 Lua environment doesn't provide.  Thanks again for sharing the source to this!
